src/Entity/SpecimenWell.php
<?php

namespace App\Entity;

use App\Util\EntityUtils;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

/**
 * Holds metadata about the relationship of a Specimen housed on a Well Plate
 *
 * @ORM\Entity
 * @ORM\Table(name="specimen_wells")
 */
class SpecimenWell
{
    public const minIntegerPosition = 1;
    public const maxIntegerPosition = 96;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Well Plate where this well is located.
     * @var WellPlate
     * @ORM\ManyToOne(targetEntity="App\Entity\WellPlate", inversedBy="wells", fetch="EAGER")
     * @ORM\JoinColumn(name="well_plate_id", referencedColumnName="id", nullable=false, onDelete="cascade")
     */
    private $wellPlate;

    /**
     * Specimen held in this well.
     *
     * @var Specimen
     * @ORM\ManyToOne(targetEntity="App\Entity\Specimen", inversedBy="wells", fetch="EAGER")
     * @ORM\JoinColumn(name="specimen_id", referencedColumnName="id", nullable=false, onDelete="cascade")
     */
    private $specimen;

    /**
     * Results of qPCR testing Specimen contained in this well.
     *
     * @var ArrayCollection|SpecimenResultQPCR[]
     * @ORM\OneToMany(targetEntity="App\Entity\SpecimenResultQPCR", mappedBy="well")
     */
    private $resultsQPCR;

    /**
     * Results of Antibody testing Specimen contained in this well.
     *
     * @var ArrayCollection|SpecimenResultAntibody[]
     * @ORM\OneToMany(targetEntity="App\Entity\SpecimenResultAntibody", mappedBy="well")
     */
    private $resultsAntibody;

    /**
     * Any identifier that identifies this well. For example, a Biobank Tube ID.
     * Uniqueness is not enforced on this field.
     *
     * @var null|string
     * @ORM\Column(name="well_identifier", type="string", length=255, nullable=true)
     */
    private $wellIdentifier;

    /**
     * Well position in alphanumeric format.
     *
     * Supports positions with and without a left-padded 0.
     * For example, these positions are equal:
     *
     *     A1 === A01
     *     A5 === A05
     *     B6 === B06
     *     B11 === B11
     *
     * @var string
     * @ORM\Column(name="position_alphanumeric", type="string", length=255, nullable=true)
     */
    private $positionAlphanumeric;

    public function __construct(WellPlate $plate, Specimen $specimen, string $position = null)
    {
        $this->resultsQPCR = new ArrayCollection();
        $this->resultsAntibody = new ArrayCollection();

        if (!self::isValidPosition($position)) {
            throw new \InvalidArgumentException('Invalid well position');
        }
        $this->positionAlphanumeric = $position;

        $this->wellPlate = $plate;
        $plate->addWell($this);

        $this->specimen = $specimen;
        $specimen->addWell($this);
    }

    public function __toString()
    {
        return $this->getWellPlatePositionDisplayString();
    }

    /**
     * Will generate a fake WellPlate if not given.
     * $position is optional.
     */
    public static function buildExample(Specimen $specimen, WellPlate $plate = null, string $position = null): self
    {
        $plate = null !== $plate ? $plate : WellPlate::buildExample('PLATE001');

        return new static($plate, $specimen, $position);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Check whether this SpecimenWell and another SpecimenWell are the same object.
     */
    public function isSame(SpecimenWell $specimenWell): bool
    {
        $specimen = $specimenWell->getSpecimen();
        if (!EntityUtils::isSameEntity($specimen, $this->specimen)) {
            return false;
        }

        $wellPlate = $specimenWell->getWellPlate();
        if (!EntityUtils::isSameEntity($wellPlate, $this->wellPlate)) {
            return false;
        }

        if (false === $this->isAtPosition($specimenWell->getPositionAlphanumeric())) {
            return false;
        }

        return $specimenWell === $this;
    }

    public function getWellPlate(): ?WellPlate
    {
        return $this->wellPlate;
    }

    public function getWellPlateBarcode(): string
    {
        return $this->wellPlate->getBarcode();
    }

    public function getSpecimen(): ?Specimen
    {
        return $this->specimen;
    }

    public function getWellIdentifier(): ?string
    {
        return $this->wellIdentifier;
    }

    public function setWellIdentifier(?string $wellIdentifier): void
    {
        $this->wellIdentifier = $wellIdentifier;
    }

    /**
     * Given a numeric position (beginning at 1), get its alphanumeric
     * equivalent such as "B4".
     *
     * Supports a 96-well plate.
     *
     *   1  2  3  4  5
     * A
     * B
     * C             * ( Given 15, Output C5)
     */
    public static function positionAlphanumericFromInt(int $positionInt): string
    {
        if ($positionInt < static::minIntegerPosition) {
            throw new \InvalidArgumentException('Position must be => ' . static::minIntegerPosition);
        }
        if ($positionInt > static::maxIntegerPosition) {
            throw new \InvalidArgumentException('Position must be <= ' . static::maxIntegerPosition);
        }

        $numRows = 8; // A-H

        $row = $positionInt % $numRows;
        if ($row === 0) {
            $row = $numRows;
        }
        $column = ceil($positionInt / $numRows);
        if ($column === 0) {
            $column = 1;
        }

        return Coordinate::stringFromColumnIndex($row) . $column;
    }

    /**
     * Whether given position is valid for specifying the Well Position.
     */
    private static function isValidPosition(?string $position): bool
    {
        if ($position === null) {
            return true;
        }

        // Empty string not allowed
        if (strlen($position) === 0) {
            return false;
        }

        return true;
    }

    public function setPositionAlphanumeric(?string $position): void
    {
        if (!self::isValidPosition($position)) {
            throw new \InvalidArgumentException('Invalid well position');
        }

        if ($this->wellPlate->hasWellAtPosition($position)) {
            throw new \InvalidArgumentException(sprintf('Position "%s" is already occupied', $position));
        }

        $this->positionAlphanumeric = $position;
    }

    /**
     * Check whether two positions are the same.
     */
    public static function isSamePosition(?string $position1, ?string $position2): bool
    {
        // Having NO position is not the *same* position
        if (null === $position1 && null === $position2) {
            return false;
        }

        // Literal same are obviously the same
        if ($position1 === $position2) {
            return true;
        }

        // Support "G05" === "G5"
        $pattern = '/^[A-G]0[1-9]$/';
        $position1Normalized = $position1;
        if (preg_match($pattern, $position1)) {
            $position1Normalized = str_replace('0', '', $position1);
        }
        $position2Normalized = $position2;
        if (preg_match($pattern, $position2)) {
            $position2Normalized = str_replace('0', '', $position2);
        }
        if ($position1Normalized === $position2Normalized) {
            return true;
        }

        return false;
    }

    /**
     * Check if this well is at given position.
     */
    public function isAtPosition(?string $checkPosition): bool
    {
        if (!self::isValidPosition($checkPosition)) {
            throw new \InvalidArgumentException('Invalid well position');
        }

        return self::isSamePosition($this->getPositionAlphanumeric(), $checkPosition);
    }

    public function getPositionAlphanumeric(): ?string
    {
        return $this->positionAlphanumeric;
    }

    /**
     * Display condensed string with Well Plate Barcode and Well Position, if available.
     */
    public function getWellPlatePositionDisplayString(): string
    {
        $barcode = $this->getWellPlateBarcode();

        // Add Barcode
        $parts = [$barcode];

        // Add Position
        $position = $this->getPositionAlphanumeric();
        if ($position !== null) {
            $parts[] = $position;
        }

        return implode(' / ', $parts);
    }

    public function addResultQPCR(SpecimenResultQPCR $result): void
    {
        if (!$this->hasResultQPCR($result)) {
            $this->resultsQPCR->add($result);
        }

        if ($this->getSpecimen()) {
            $this->getSpecimen()->updateStatusWhenResultsSet();
        }
    }

    public function removeResultQPCR(SpecimenResultQPCR $result): void
    {
        $removeKey = null;

        foreach ($this->resultsQPCR as $key => $existingResult) {
            if ($removeKey !== null) continue;
            if (EntityUtils::isSameEntity($result, $existingResult)) {
                $removeKey = $key;
            }
        }

        if ($removeKey !== null) {
            $this->resultsQPCR->remove($removeKey);
        }
    }

    public function hasResultQPCR(SpecimenResultQPCR $result): bool
    {
        foreach ($this->resultsQPCR as $existingResult) {
            if (EntityUtils::isSameEntity($result, $existingResult)) {
                return true;
            }
        }

        return false;
    }

    public function hasResultsQPCR(): bool
    {
        return !$this->resultsQPCR->isEmpty();
    }

    /**
     * @return SpecimenResultQPCR[]
     */
    public function getResultsQPCR(): array
    {
        return $this->resultsQPCR->getValues();
    }

    public function addResultAntibody(SpecimenResultAntibody $result): void
    {
        if (!$this->hasResultAntibody($result)) {
            $this->resultsAntibody->add($result);
        }

        if ($this->getSpecimen()) {

src/Controller/SpecimenController.php
<?php

namespace App\Controller;

use App\Entity\AuditLog;
use App\Entity\Specimen;
use App\Form\SpecimenFilterForm;
use App\Form\SpecimenForm;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Interact with Specimens.
 *
 * @Route(path="/specimens")
 */
class SpecimenController extends AbstractController
{
    /**
     * List all Specimens
     *
     * @Route(path="/", methods={"GET"})
     */
    public function list(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_SPECIMEN_VIEW');

        // Explicitly use FormFactory to remove form name from GET params for cleaner URL
        $filterForm = $this->get('form.factory')->createNamed('', SpecimenFilterForm::class);
        $filterForm->handleRequest($request);
        $formData = [];
        if ($filterForm->isSubmitted() && $filterForm->isValid()) {
            $formData = $filterForm->getData();
        }

        $specimens = $this->getDoctrine()
            ->getRepository(Specimen::class)
            ->filterByFormData($formData);

        return $this->render('specimen/specimen-list.html.twig', [
            'specimens' => $specimens,
            'filterForm' => $filterForm->createView(),
        ]);
    }

    /**
     * View a single Specimen.
     *
     * @Route("/{accessionId}", methods={"GET", "POST"})
     */
    public function view(string $accessionId)
    {
        $this->denyAccessUnlessGranted('ROLE_SPECIMEN_VIEW');

        $specimen = $this->findSpecimen($accessionId);

        $auditLogs = $this->getDoctrine()
            ->getRepository(AuditLog::class)
            ->getLogEntries($specimen);

        return $this->render('specimen/specimen-view.html.twig', [
            'specimen' => $specimen,
            'auditLogs' => $auditLogs,
        ]);
    }

    /**
     * Create a single new Specimen
     *
     * @Route(path="/new", methods={"GET", "POST"})
     */
    public function new(Request $request) : Response
    {
        $this->denyAccessUnlessGranted('ROLE_SPECIMEN_EDIT');

        $form = $this->createForm(SpecimenForm::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Specimen $specimen */
            $specimen = $form->getData();

            $em = $this->getDoctrine()->getManager();
            $em->persist($specimen);
            $em->flush();

            return $this->redirectToRoute('app_specimen_view', [
                'accessionId' => $specimen->getAccessionId(),
            ]);
        }

        return $this->render('specimen/specimen-form.html.twig', [
            'new' => true,
            'form'=> $form->createView(),
        ]);
    }

    /**
     * Edit a single Specimen.
     *
     * @Route("/{accessionId}/edit", methods={"GET", "POST"})
     */
    public function edit(string $accessionId, Request $request) : Response
    {
        $this->denyAccessUnlessGranted('ROLE_SPECIMEN_EDIT');

        $specimen = $this->findSpecimen($accessionId);

        $form = $this->createForm(SpecimenForm::class, $specimen);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('app_specimen_view', [
                'accessionId' => $specimen->getAccessionId(),
            ]);
        }

        return $this->render('specimen/specimen-form.html.twig', [
            'new' => false,
            'form' => $form->createView(),
            'specimen' => $specimen,
        ]);
    }

    private function findSpecimen($id): Specimen
    {
        $s = $this->getDoctrine()
            ->getRepository(Specimen::class)
            ->findOneByAnyId($id);

        if (!$s) {
            throw new NotFoundHttpException('Cannot find Specimen');
        }

        return $s;
    }
}

templates/specimen/specimen-form.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}
    {% if new %} New Specimen {% else %} Edit Specimen {{ specimen.accessionId }} {% endif %}
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-body">
                {{ form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/specimen/specimen-list-table.html.twig
{% block body %}
    {% set userCanEditSpecimens = is_granted('ROLE_SPECIMEN_EDIT') %}
    {% set userCanViewWellPlates = is_granted('ROLE_WELL_PLATE_VIEW') %}
<table id="specimen-list-table" class="table table-bordered table-hover">
    <thead>
        <tr>
            {% if userCanEditSpecimens %}<th class="no-sort">&nbsp;</th>{% endif %}
            <th>Accession ID</th>
            <th>Participant Group</th>
            <th>Type</th>
            <th>Collection Time</th>
            <th>Well Plate</th>
            <th>CLIA Testing Recommended?</th>
            <th>Status</th>
        </tr>

        <tr id="specimen-filter-row" class="filter-header-row">
            {% if userCanEditSpecimens %}<th><!-- Edit --></th>{% endif %}
            <th><!-- Accession ID --></th>
            <th>
                <!-- Participant Group -->
                {{ form_row(filterForm.participantGroup, {
                    'attr': {
                        'class': 'submit-on-change',
                        'form': 'filter-form'
                    },
                    'row_attr': {'class': 'no-margin'}
                }) }}
            </th>
            <th>
                <!-- Type -->
                {{ form_row(filterForm.type, {
                    'attr': {
                        'class': 'submit-on-change',
                        'form': 'filter-form'
                    },
                    'row_attr': {'class': 'no-margin'}
                }) }}
            </th>
            <th>
                <!-- Collection Time -->
                {{ form_row(filterForm.collectedAt, {
                    'attr': {
                        'class': 'filter-datepicker',
                        'form': 'filter-form'
                    },
                    'row_attr': {'class': 'no-margin'}
                }) }}
            </th>
            <th>
                <!-- Well Plate -->
                {{ form_row(filterForm.wellPlate, {
                    'attr': {
                        'class': 'submit-on-change',
                        'form': 'filter-form'
                    },
                    'row_attr': {'class': 'no-margin'}
                }) }}
            </th>
            <th><!-- CLIA Testing Recommended? --></th>
            <th>
                <!-- Status -->
                {{ form_row(filterForm.status, {
                    'attr': {
                        'class': 'submit-on-change',
                        'form': 'filter-form'
                    },
                    'row_attr': {'class': 'no-margin'}
                }) }}
            </th>
        </tr>
    </thead>
    <tbody>
    {% for specimen in specimens %}
        <tr>
            {% if userCanEditSpecimens %}
            <td>
                <a href="{{ path('app_specimen_edit', {accessionId: specimen.accessionId}) }}">Edit</a>
            </td>
            {% endif %}
            <td>
                <a href="{{ path('app_specimen_view', {accessionId: specimen.accessionId}) }}">{{ specimen.accessionId }}</a>
            </td>
            <td>{{ specimen.participantGroup }}</td>
            <td>{{ specimen.typeText }}</td>
            {% if specimen.collectedAt is empty %}
                <td></td>
            {% else %}
                <td class="nowrap-cell" data-sort="{{ specimen.collectedAt|date("U")|e("html_attr") }}">{{ specimen.collectedAt | date("Y-m-d H:ia") }}</td>
            {% endif %}
            <td class="nowrap-cell">
                {% for well in specimen.wells %}
                    {% if userCanViewWellPlates %}
                    <a href="{{ path('well_plate_view', {barcode: well.wellPlateBarcode}) }}">{{ well.wellPlatePositionDisplayString }}</a>
                    {% else %}
                    {{ well.wellPlatePositionDisplayString }}
                    {% endif %}
                    <br>
                {% endfor %}
            </td>
            <td>{{ specimen.cliaTestingRecommendedText }}</td>
            <td>{{ specimen.statusText }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{{ form_start(filterForm, {
    "attr": {"id":"filter-form"}
}) }}
{{ form_end(filterForm) }}

<script type="application/javascript">
    // Enable DataTable for table of Specimens
    $('#specimen-list-table').DataTable({
        // Disable global table search field. We provide our own column search filters.
        searching: false,

        // Disable paging so users can view all records at once.
        paging: false,

        // Display info line before table instead of after it.
        // Also hides {pagination}, {length} and {filter} blocks because we don't use them.
        // Renders blocks as:
        // {information}
        // {table}
        // https://datatables.net/reference/option/dom
        dom: 'it',

        // Re-word {information} block to only show record count.
        // Normally this area includes page counts but our paging is disabled,
        // so just display the full count.
        // https://datatables.net/reference/option/infoCallback
        infoCallback: function(settings, start, end, max, total, pre) {
            return "<strong>Found " + total + " records</strong>";
        },

        // Disable some features for select columns.
        // https://datatables.net/reference/option/columnDefs
        columnDefs: [
            {
                targets: 'no-sort',
                orderable: false
            }
        ],

        // Default sort on Collection Time column with most recent at top
        order: [[4, 'desc']],

        // Sort columns using first <thead> row
        // instead of last row (which contain our filter form widgets)
        "bSortCellsTop": true,

        // Text displayed when no results found
        "language": {
            "emptyTable": "<em>No results found. Remove filters to display records.</em>"
        }
    });

    // Enable Date Picker for filter elements
    let datepickers = $('.filter-datepicker').datepicker({
        format: 'yyyy-mm-dd',
        clearBtn: true,
        todayBtn: "linked",
        todayHighlight: true
    });

    // Callback to submit
    let executeFilterSearch = function() {
        $("#filter-form").submit();
    };

    // Submit filter form when datepicker closes.
    // Does NOT use .submit-on-change class because datepicker updates input
    // value when selecting from calendar.
    datepickers.on("hide", executeFilterSearch);

    // Submit filter form when a form widget changes
    $('#specimen-filter-row .submit-on-change').on('change', executeFilterSearch);

    // Any filter form widget with a value appears visually highlighted
    // so easier to see when filters affect search results
    $('#specimen-filter-row input, #specimen-filter-row select').each(function() {
        let cssClassWhenHasValue = 'filter-with-value';

        let formWidget = $(this);
        if (formWidget.val() !== '') {
            formWidget.addClass(cssClassWhenHasValue);
        } else {
            formWidget.removeClass(cssClassWhenHasValue);
        }
    });
</script>
{% endblock %}

templates/specimen/specimen-list.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}Specimens{% endblock %}

{% block body %}
{% if is_granted('ROLE_SPECIMEN_EDIT') %}
<div class="row margin-bottom">
    <div class="col-md-12">
        <div class="pull-right">
            <a href="{{ path('app_specimen_new') }}" class="btn btn-primary pull-right"><i class="fa fa-fw fa-plus"></i> New Specimen</a>
        </div>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body table-responsive">
                {% include('specimen/specimen-list-table.html.twig') %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/specimen/specimen-view.html.twig
{% extends 'base.html.twig' %}
{% import 'results/qpcr/macros.html.twig' as resultMacros %}
{% set userCanEditSpecimens = is_granted('ROLE_SPECIMEN_EDIT') %}
{% set userCanViewResults = is_granted('ROLE_RESULTS_VIEW') %}
{% set userCanEditResults = is_granted('ROLE_RESULTS_EDIT') %}
{% set bloodConstant = constant('App\\Entity\\Specimen::TYPE_BLOOD') %}
{% set salivaConstant = constant('App\\Entity\\Specimen::TYPE_SALIVA') %}

{% block page_title %}
    <i class="fa fa-flask"></i> Specimen {{ specimen.accessionId }}
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">
                    General

                    {% if userCanEditSpecimens %}
                    <a href="{{ path('app_specimen_edit', {accessionId: specimen.accessionId}) }}" class="btn btn-primary btn-xs" style="margin-left:8px"><i class="fa fa-fw fa-edit"></i> Edit</a>
                    {% endif %}
                </h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>Accession ID</dt><dd>{{ specimen.accessionId }}</dd>
                    <dt>Participation Group</dt><dd><a href="{{ path('app_participant_group_view', {title: specimen.participantGroup.title}) }}">{{ specimen.participantGroup }}</a></dd>
                    <dt>Type</dt><dd>{{ specimen.typeText }}</dd>
                    <dt>Well Plate</dt><dd>
                        {% for well in specimen.wells %}
                        <a href="{{ path('well_plate_view', {barcode: well.wellPlateBarcode}) }}">{{ well.wellPlatePositionDisplayString }}</a><br>
                        {% endfor %}
                    </dd>
                    <dt>Collection Time</dt><dd>{{ specimen.collectedAt is empty ? "" : specimen.collectedAt|date("Y-m-d g:ia") }}</dd>
                    {% if specimen.cliaTestingRecommendedText %}
                    <dt>CLIA Testing Recommended?</dt><dd>{{ specimen.cliaTestingRecommendedText }}</dd>
                    {% endif %}
                    <dt>Status</dt><dd>{{ specimen.statusText }}</dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        {% include 'audit-history.html.twig' with {auditLogs: auditLogs} %}
    </div>

</div>

{% if userCanViewResults %}

{% if specimen.type == salivaConstant %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Viral Results

                    {% if userCanEditResults %}
                    <a href="{{ path('results_qpcr_new', {specimenAccessionId: specimen.accessionId}) }}" class="btn btn-success btn-xs" style="margin-left:8px"><i class="fa fa-fw fa-plus"></i> New</a>
                    {% endif %}
                </h3>
            </div>
            <div class="box-body">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        {% if userCanEditResults %}<th>&nbsp;<!-- Edit --></th>{% endif %}
                        <th>&nbsp;<!-- View --></th>
                        <th>Conclusion</th>
                        <th>Well Plate Barcode</th>
                        <th>Well Position</th>
                        <th>Ct / Amp Score</th>
                        <th>Reported At</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for result in specimen.qPCRResults %}
                        <tr>
                            {% if userCanEditResults %}
                            <td>
                                <a href="{{ path('results_qpcr_edit', {id: result.id, accessionId: specimen.accessionId}) }}">Edit</a>
                            </td>
                            {% endif %}
                            <td><a href="{{ path('results_qpcr_view', {id: result.id}) }}">View</a></td>
                            <td>{{ result.conclusionText }}</td>
                            <td>{{ result.wellPlateBarcode }}</td>
                            <td>{{ result.wellPosition }}</td>
                            <td>
                                {{ resultMacros.renderCtAmpScore(result) }}
                            </td>
                            <td>{{ result.createdAt | date("Y-m-d g:ia") }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}{# End viralResults #}

{% if specimen.type == bloodConstant %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Antibody Results

                    {% if userCanEditResults %}
                    <a href="{{ path('results_antibody_new', {specimenAccessionId: specimen.accessionId}) }}" class="btn btn-success btn-xs" style="margin-left:8px"><i class="fa fa-fw fa-plus"></i> New</a>
                    {% endif %}
                </h3>
            </div>
            <div class="box-body">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        {% if userCanEditResults %}<th>&nbsp;<!-- Edit --></th>{% endif %}
                        <th>&nbsp;<!-- View --></th>
                        <th>Conclusion</th>
                        <th>Signal</th>
                        <th>Well Plate Barcode</th>
                        <th>Well Position</th>
                        <th>Well ID</th>
                        <th>Reported At</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for result in specimen.antibodyResults %}
                        <tr>
                            {% if userCanEditResults %}
                            <td>
                                <a href="{{ path('results_antibody_edit', {id: result.id, accessionId: specimen.accessionId}) }}">Edit</a>
                            </td>
                            {% endif %}
                            <td><a href="{{ path('results_antibody_view', {id: result.id}) }}">View</a></td>
                            <td>{{ result.conclusionText }}</td>
                            <td>{{ result.signal }}</td>
                            <td>{{ result.wellPlateBarcode }}</td>
                            <td>{{ result.wellPosition }}</td>
                            <td>{{ result.wellIdentifier }}</td>
                            <td>{{ result.createdAt | date("Y-m-d g:ia") }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}{# End viralResults #}

{% endif %}{# End if userCanViewResults #}

{% endblock %}