src/Entity/AppUser.php
<?php

namespace App\Entity;

use App\Traits\TimestampableEntity;
use App\Util\AuditLogUtils;
use App\Util\StringUtils;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Role\RoleHierarchyInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AppUserRepository")
 * @ORM\Table(name="users")
 *
 * @Gedmo\Loggable(logEntryClass="App\Entity\AuditLog")
 */
class AppUser implements UserInterface
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="username", type="string", length=180, unique=true, nullable=false)
     *
     * @Gedmo\Versioned
     */
    private $username;

    /**
     * @ORM\Column(name="roles", type="json")
     *
     * @Gedmo\Versioned
     */
    private $roles = [];

    /**
     * @var string The hashed password (will be null if this user came from LDAP)
     * @ORM\Column(name="password", type="string", nullable=true)
     */
    private $password;

    /**
     * @var bool If true, this user is managed by LDAP and should be authenticated against it
     * @ORM\Column(name="is_ldap_user", type="boolean")
     *
     * @Gedmo\Versioned
     */
    private $isLdapUser = false;

    /**
     * @var boolean Whether the user has ever logged in
     *
     * @ORM\Column(name="has_logged_in", type="boolean", nullable=false)
     */
    protected $hasLoggedIn;

    /**
     * @var \DateTimeImmutable The first time the user logged in
     *
     * @ORM\Column(name="first_logged_in_at", type="datetime_immutable", nullable=true)
     */
    protected $firstLoggedInAt;

    /**
     * @var \DateTimeImmutable The most recent time the user logged in
     *
     * @ORM\Column(name="last_logged_in_at", type="datetime_immutable", nullable=true)
     */
    protected $lastLoggedInAt;

    /**
     * @var string User's preferred display name
     *
     * @ORM\Column(name="display_name", type="string", length=255, nullable=true)
     *
     * @Gedmo\Versioned
     */
    protected $displayName;

    /**
     * @var string Email address for contacting this user
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     *
     * @Gedmo\Versioned
     */
    protected $email;

    /**
     * @var string User's title within the organization
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     *
     * @Gedmo\Versioned
     */
    protected $title;

    public function __construct(string $username)
    {
        $this->hasLoggedIn = false;
        $this->username = $username;

        // All users should at least have ROLE_USER
        $this->roles = ['ROLE_USER'];
    }

    /**
     * This method returns true if this user has been granted access to the application
     *
     * Users are able to log in if they've been granted any role in addition to ROLE_USER
     */
    public function isProvisioned() : bool
    {
        foreach ($this->roles as $role) {
            if ($role != 'ROLE_USER') return true;
        }

        return false;
    }

    /**
     * Convert audit log field changes from internal format to human-readable format.
     *
     * The input to this method will be a map of properties and their raw values
     *
     *     [
     *         "status" => "RESULTS", // STATUS_RESULTS constant value
     *         "createdAt" => \DateTime(...),
     *     ]
     *
     * This method should convert the changes to human-readable values like this:
     *
     *     [
     *         "status" => "Results Available",
     *         "Created At" => AuditLogUtils::getHumanReadableString($value)
     *     ]
     *
     * @param array $changes Keys are internal entity propertyNames, Values are internal entity values
     * @return mixed[] Keys are human-readable field names, Values are human-readable strings
     */
    public static function makeHumanReadableAuditLogFieldChanges(array $changes): array
    {
        $return = [];

        foreach ($changes as $fieldId => $value) {
            $hrProperty = StringUtils::camelCaseToTitleCase($fieldId);
            $hrValue = AuditLogUtils::getHumanReadableString($value);

            $return[$hrProperty] = $hrValue;
        }

        return $return;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Whether user has been granted this role in the admin interface.
     * Does NOT account for inherited roles/permissions.
     */
    public function hasRoleExplicit(string $role): bool
    {
        return in_array($role, $this->roles);
    }

    /**
     * Whether user has been granted this role, either explicitly or through
     * inherited roles.
     */
    public function hasRole(RoleHierarchyInterface $hierarchy, string $role): bool
    {
        return in_array($role, $hierarchy->getReachableRoleNames($this->roles));
    }

    public function addRole(string $role): self
    {
        $this->roles[] = $role;
        $this->roles = array_unique($this->roles);

        return $this;
    }

    public function removeRole(string $role): void
    {
        $this->roles = array_filter($this->roles, function(string $currentRole) use ($role) {
            return $currentRole !== $role;
        });
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isLdapUser(): bool
    {
        return $this->isLdapUser;
    }

    public function setIsLdapUser(bool $isLdapUser): void
    {
        $this->isLdapUser = $isLdapUser;
    }

    public function isHasLoggedIn(): bool
    {
        return $this->hasLoggedIn;
    }

    public function setHasLoggedIn(bool $hasLoggedIn): void
    {
        // Update firstLoggedInAt if this is the first time they've logged in
        if ($hasLoggedIn && $this->hasLoggedIn === false && $this->firstLoggedInAt === null) {
            $this->firstLoggedInAt = new \DateTimeImmutable();
        }

        $this->hasLoggedIn = $hasLoggedIn;
    }

    public function getFirstLoggedInAt(): ?\DateTimeImmutable
    {
        return $this->firstLoggedInAt;
    }

    public function setFirstLoggedInAt(?\DateTimeImmutable $firstLoggedInAt): void
    {
        $this->firstLoggedInAt = $firstLoggedInAt;
    }

    public function getLastLoggedInAt(): ?\DateTimeImmutable
    {
        return $this->lastLoggedInAt;
    }

    public function setLastLoggedInAt(?\DateTimeImmutable $lastLoggedInAt): void
    {
        $this->lastLoggedInAt = $lastLoggedInAt;
    }

    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }
}

src/Form/UserType.php
<?php


namespace App\Form;


use App\Entity\AppUser;
use App\Util\AppPermissions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;

class UserType extends AbstractType
{
    /** @var AccessDecisionManagerInterface */
    protected $accessDecisionManager;

    /**
     * If known, the user being edited. This is used to determine which permissions they have so the
     * permission checkboxes can be set correctly
     *
     * @var AppUser
     */
    protected $user;

    public function __construct(AccessDecisionManagerInterface $accessDecisionManager = null)
    {
        $this->accessDecisionManager = $accessDecisionManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['data'] instanceof AppUser) {
            $this->user = $options['data'];
        }
        else {
            throw new \InvalidArgumentException('Form data must be an AppUser');
        }

        $ldapLockedFieldHelp = '';
        if ($this->user->isLdapUser()) {
            $ldapLockedFieldHelp = 'This field cannot be changed for LDAP users';
        }

        $builder
            ->add('username', TextType::class, [
                'disabled' => $this->user->isLdapUser(),
                'help' => $ldapLockedFieldHelp,
            ])
            ->add('displayName', TextType::class, [
                'required' => false,
                'disabled' => $this->user->isLdapUser(),
                'help' => $ldapLockedFieldHelp,
            ])
            ->add('email', EmailType::class, [
                'required' => false,
                'disabled' => $this->user->isLdapUser(),
                'help' => $ldapLockedFieldHelp,
            ])
        ;

        // Search DEPENDS_ON_AVAILABLE_ROLES for other places needing updates when changing this list
        // Permissions
        $this->addRoleField($builder, 'ROLE_ADMIN', 'System Admin');

        $this->addRoleField($builder, 'ROLE_CONFIG_ALL', 'Configuration Access');

        $this->addRoleField($builder, 'ROLE_KIOSK_UI', 'Kiosk Access');

        $this->addRoleField($builder, 'ROLE_PARTICIPANT_GROUP_EDIT', 'Participant Groups: Edit');
        $this->addRoleField($builder, 'ROLE_PARTICIPANT_GROUP_VIEW', 'Participant Groups: View');

        $this->addRoleField($builder, 'ROLE_TUBE_CHECK_IN', 'Tube: Check In');

        $this->addRoleField($builder, 'ROLE_RESULTS_EDIT', 'Results: Upload and Edit');
        $this->addRoleField($builder, 'ROLE_RESULTS_VIEW', 'Results: View');

        $this->addRoleField($builder, 'ROLE_WELL_PLATE_EDIT', 'Well Plates: Edit');
        $this->addRoleField($builder, 'ROLE_WELL_PLATE_VIEW', 'Well Plates: View');

        $this->addRoleField($builder, 'ROLE_PRINT_TUBE_LABELS', 'Print: Tube Labels');
        $this->addRoleField($builder, 'ROLE_PRINT_GROUP_LABELS', 'Print: Group Labels');

        $this->addRoleField($builder, 'ROLE_NOTIFY_ABOUT_VIRAL_RESULTS', 'Notifications: Group Testing Recommended');
        $this->addRoleField($builder, 'ROLE_NOTIFY_ABOUT_ANTIBODY_RESULTS', 'Notifications: Antibody Testing Results');

        $builder
            ->add('Save', SubmitType::class, [
                'label' => 'Save',
                'attr' => ['class' => 'btn-primary'],
            ])
            ->getForm();
    }

    protected function addRoleField(FormBuilderInterface $builder, $role, $label)
    {
        $fieldName = sprintf('hasRole_%s', $role);
        $hasRole = $this->hasRole($role);
        $roleIsNotExplicit = $this->userDoesNotHaveExplicitRole($role);

        $help = null;
        $disabled = false;

        // If they have the role but it wasn't granted explicitly, do not let them remove the permission
        // and make it clear why they cannot
        if ($hasRole && $roleIsNotExplicit) {
            $disabled = true;
            $help = 'This ability is granted by another permission and cannot be removed.';
        }

        $builder->add($fieldName, CheckboxType::class, [
            'mapped' => false,          // does not directly map to an entity field
            'required' => false,        // if this is true the box must be checked
            'label' => $label,
            'data' => $hasRole,         // Check the box if they have the role
            'disabled' => $disabled,
            'help' => $help,
        ]);
    }

    protected function userDoesNotHaveExplicitRole($role)
    {
        if (!$this->accessDecisionManager) {
            throw new \LogicException('Attempted to call hasRole with no accessDecisionManager defined. Autowiring failed?');
        }
        if (!$this->user) {
            throw new \InvalidArgumentException('Cannot call this method without a user set.');
        }

        return !AppPermissions::userHasExplicitRole($this->user, $role);
    }

    protected function hasExplicitRole($role)
    {
        if (!$this->user) {
            throw new \InvalidArgumentException('Cannot call this method without a user set.');
        }

        return AppPermissions::userHasExplicitRole($this->user, $role);
    }

    protected function hasRole($role)
    {
        if (!$this->accessDecisionManager) {
            throw new \LogicException('Attempted to call hasRole with no accessDecisionManager defined. Autowiring failed?');
        }
        if (!$this->user) {
            throw new \InvalidArgumentException('Cannot call this method without a user set.');
        }

        return AppPermissions::userHasInheritedRole($this->accessDecisionManager, $this->user, $role);
    }
}

templates/user/change-password.twig
{% extends 'base.html.twig' %}

{% block page_title %}Change Password{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    <dl>
                        <dt>Username</dt>
                        <dd>{{ user.username }}</dd>
                    </dl>

                    {{ form(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/form.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}
    <i class="fa fa-user"></i> {% if user.id %} Edit User {{ user.username }} {% else %} New User {% endif %}
{% endblock %}

{% block body %}
    <div class="alert alert-warning" role="alert">
        <b>Warning:</b> Changing a user's permissions will log them out!
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    {{ form(form) }}
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Account</h3>
                </div>
                <div class="box-body">
                    {% if not user.ldapUser %}
                        <strong>Password:</strong> <a href="{{ path("user_change_password", { username: user.username }) }}" class="btn btn-xs btn-default" role="button"><i class="fa fa-lock"></i> Change Password</a><br><br>
                    {% endif %}
                    <strong>Last Login:</strong> {{ user.hasLoggedIn ? user.lastLoggedInAt|date('Y-m-d g:ia') : '-- Never --' }}
                </div>
            </div>

            {% include 'audit-history.html.twig' with {auditLogs: auditLogs} %}
        </div>
    </div>
{% endblock %}

templates/user/list.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}Users{% endblock %}

{% block body %}
    <div class="row margin-bottom">
        <div class="col-xs-12">
            <a href="{{ path('user_new') }}" class="btn btn-primary pull-right"><i class="fa fa-fw fa-plus"></i> Add User</a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body table-responsive">
                    {% include 'user/user-table.html.twig' with { users: users, rolesByUser: rolesByUser } %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}Add User{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    {{ form(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/user-table.html.twig
{# Search for DEPENDS_ON_AVAILABLE_ROLES for other locations that depend on these permissions #}
<table id="users-list-table" class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th class="text-center bg-gray">System Admin</th>
        <th class="text-center">Configuration</th>
        <th class="text-center bg-gray">Kiosk Access</th>
        <th colspan="2" class="text-center">Participant Groups</th>
        <th class="text-center bg-gray">Specimens</th>
        <th colspan="2" class="text-center">Results</th>
        <th colspan="2" class="text-center bg-gray">Well Plates</th>
        <th colspan="2" class="text-center">Print</th>
        <th colspan="2" class="text-center bg-gray">Notifications</th>
    </tr>
    <tr>
        <th>Username</th>
        <th>Display Name</th>
        <th class="bg-gray">&nbsp;{# System Admin #}</th>
        <th>&nbsp;{# Config #}</th>
        <th class="text-center bg-gray">&nbsp;{# Kiosk UI #}</th>
        {# Participant Groups #}
        <th class="text-center">Edit</th>
        <th class="text-center">View</th>
        {# Specimens #}
        <th class="text-center bg-gray">Check In</th>
        {# Results #}
        <th class="text-center">Upload and Edit</th>
        <th class="text-center">View</th>
        {# Well Plates #}
        <th class="text-center bg-gray">Edit</th>
        <th class="text-center bg-gray">View</th>
        {# Print #}
        <th class="text-center">Tube Labels</th>
        <th class="text-center">Group Labels</th>
        {# Notifications #}
        <th class="text-center bg-gray">Viral Results</th>
        <th class="text-center bg-gray">Antibody Results</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>
                <a href="{{ path('user_edit', {username: user.username}) }}">{{ user.username}}</a>
            </td>
            <td>{{ user.displayName }}</td>
            {# System Admin #}
            <td class="text-center bg-gray">{% if 'ROLE_ADMIN' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Config #}
            <td class="text-center">{% if 'ROLE_CONFIG_ALL' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Kiosk UI #}
            <td class="text-center bg-gray">{% if 'ROLE_KIOSK_UI' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Participant Groups #}
            <td class="text-center">{% if 'ROLE_PARTICIPANT_GROUP_EDIT' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            <td class="text-center">{% if 'ROLE_PARTICIPANT_GROUP_VIEW' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Specimens #}
            <td class="text-center bg-gray">{% if 'ROLE_TUBE_CHECK_IN' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Results #}
            <td class="text-center">{% if 'ROLE_RESULTS_EDIT' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            <td class="text-center">{% if 'ROLE_RESULTS_VIEW' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Well Plates #}
            <td class="text-center bg-gray">{% if 'ROLE_WELL_PLATE_EDIT' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            <td class="text-center bg-gray">{% if 'ROLE_WELL_PLATE_VIEW' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Print #}
            <td class="text-center">{% if 'ROLE_PRINT_TUBE_LABELS' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            <td class="text-center">{% if 'ROLE_PRINT_GROUP_LABELS' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            {# Notifications #}
            <td class="text-center bg-gray">{% if 'ROLE_NOTIFY_ABOUT_VIRAL_RESULTS' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
            <td class="text-center bg-gray">{% if 'ROLE_NOTIFY_ABOUT_ANTIBODY_RESULTS' in rolesByUser[user.username] %}<i class="fa fa-check-square text-green"></i>{% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<script type="application/javascript">
    // Enable DataTable for table of Users
    $('#users-list-table').DataTable({
        // Disable paging so users can view all records at once.
        paging: false,

        // Display info line before table instead of after it.
        // Also hides {pagination}, {length} blocks because we don't use them.
        // Renders blocks as:
        // {filter}
        // {information}
        // {table}
        // https://datatables.net/reference/option/dom
        dom: 'fit',

        // Re-word {information} block to only show record count.
        // Normally this area includes page counts but our paging is disabled,
        // so just display the full count.
        // https://datatables.net/reference/option/infoCallback
        infoCallback: function(settings, start, end, max, total, pre) {
            return "<strong>Displaying " + total + " records</strong>";
        },

        // Default sort on Name column alphabetically
        order: [[1, 'asc']],

        // Text displayed when no results found
        "language": {
            "emptyTable": "<em>No results found. Remove filters to display records.</em>"
        }
    });
</script>